server:
  host: localhost
  port: "3001"

gemini:
  api_key: ""

cors:
  origin: "http://localhost:5173"

database:
  host: localhost
  port: "3306"
  user: root
  password: ""
  name: invoice_scan

worker:
  inputs:
    name: ABC
    age: 11

a: ["0", 1.2E-5, 3.2, 4.1]
b: ["abc", 1, 2, 3]