server:
  host: localhost
  port: "3001"
  ssl:
    enabled: false
    cert_file: "./ssl/cert.pem"
    key_file: "./ssl/key.pem"

gemini:
  api_key: ""

cors:
  origin: "http://localhost:5173"

database:
  host: localhost
  port: "3306"
  user: root
  password: ""
  name: invoice_scan

storage:
  upload_path: "./uploads"
  base_url: "http://localhost:3001"